import {
  Calculator,
  Calendar,
  Clock,
  DollarSign,
  FileText,
  Globe,
  Heart,
  Image,
  Key,
  ListTodo,
  Percent,
  QrCode,
  Ruler,
  Scale,
  Sparkles,
  Target,
  TimerReset,
  TrendingUp,
} from "lucide-react";

export const tools = [
  {
    id: "prompt-generator",
    name: "Prompt Generator",
    description: "Generate powerful, tailored AI prompts instantly for various use-cases",
    icon: Sparkles,
    category: "AI Tools",
    popular: true,
  },
  {
    id: "image-tools",
    name: "Image Tools",
    description: "Professional image processing tools - resize, convert, compress, and more",
    icon: Image,
    category: "Utility",
    popular: true,
  },
  {
    id: "qr-code-generator",
    name: "QR Code Generator",
    description: "Create custom QR codes for URLs, text, emails, and more",
    icon: QrCode,
    category: "Utility",
    popular: true,
  },
  {
    id: "emi-calculator",
    name: "EMI Calculator",
    description: "Quickly estimate monthly EMIs for any loan with interest and tenure",
    icon: Calculator,
    category: "Financial",
    popular: true,
  },
  {
    id: "age-calculator",
    name: "Age Calculator",
    description: "Calculate exact age in years, months, and days",
    icon: Calendar,
    category: "Date & Time",
    popular: false,
  },
  {
    id: "gst-calculator",
    name: "GST Calculator",
    description: "Easily compute GST amounts, reverse GST, and inclusive/exclusive tax totals",
    icon: Percent,
    category: "Financial",
    popular: false,
  },
  {
    id: "bmi-calculator",
    name: "BMI Calculator",
    description: "Calculate Body Mass Index and health status",
    icon: Heart,
    category: "Health",
    popular: false,
  },
  {
    id: "dob-calculator",
    name: "DOB Calculator",
    description: "Find date of birth from current age",
    icon: Clock,
    category: "Date & Time",
    popular: false,
  },
  {
    id: "percentage-calculator",
    name: "Percentage Calculator",
    description: "Calculate percentages, increase, and decrease",
    icon: TrendingUp,
    category: "Math",
    popular: false,
  },
  {
    id: "unit-converter",
    name: "Unit Converter",
    description: "Convert between different units of measurement",
    icon: Scale,
    category: "Conversion",
    popular: false,
  },
  {
    id: "area-calculator",
    name: "Area Calculator",
    description: "Calculate area of various geometric shapes",
    icon: Ruler,
    category: "Math",
    popular: false,
  },
  {
    id: "tip-calculator",
    name: "Tip Calculator",
    description: "Calculate restaurant tips and split bills effortlessly with friends",
    icon: DollarSign,
    category: "Financial",
    popular: false,
  },
  {
    id: "goal-tracker",
    name: "Goal Tracker",
    description: "Plan and monitor your savings journey toward financial goals",
    icon: Target,
    category: "Planning",
    popular: true,
  },
  {
    id: "todo-list",
    name: "ToDo List",
    description: "Stay organized and productive with a simple todo list",
    icon: ListTodo,
    category: "Planning",
    popular: true,
  },
  {
    id: "currency-converter",
    name: "Currency Converter",
    description: "Convert between different currencies with real-time exchange rates",
    icon: DollarSign,
    category: "Financial",
    popular: true,
  },
  {
    id: "timezone-converter",
    name: "Timezone Converter",
    description: "Convert time between different timezones and track world clocks",
    icon: Globe,
    category: "Date & Time",
    popular: false,
  },
  {
    id: "timers-tools",
    name: "Timers",
    description: "Track time with countdown and stopwatch features",
    icon: TimerReset,
    category: "Date & Time",
    popular: false,
  },
  {
    id: "password-generator",
    name: "Password Generator",
    description: "Generate secure, customizable passwords with strength analysis",
    icon: Key,
    category: "Security",
    popular: true,
  },
  {
    id: "invoice-generator",
    name: "Invoice Generator",
    description: "Create professional invoices with multiple currencies, templates, and PDF export",
    icon: FileText,
    category: "Business",
    popular: true,
  },
];
